# Generated by Django 3.2.6 on 2021-08-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vera', '0002_auto_20210810_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
