# Generated by Django 3.2.6 on 2021-08-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vera', '0003_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
    ]
